services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
  
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    ports:
      - "8085:8080"
    environment:
      R2DBC_URL: r2dbc:postgresql://db:5432/media_db
      R2DBC_USERNAME: postgres
      R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/media_db
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: media
    depends_on:
      - db
      - minio

volumes:
  postgres_data:
  minio_data: