services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      R2DBC_URL: r2dbc:postgresql://db:5432/notification_db
      R2DBC_USERNAME: postgres
      R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/notification_db
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      SMTP_ADDRESS: khitrov.ceeeb@yandex.ru
      SMTP_PASSWORD: ifnuqsrblwkaapmf
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      
volumes:
  postgres_data:

  