services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trip_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      R2DBC_URL: r2dbc:postgresql://db:5432/trip_db
      R2DBC_USERNAME: postgres
      R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/trip_db
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      TRIP_SERVICE_BASE_URL: http://localhost:8082

volumes:
  postgres_data: