spring:
  application:
    name: profile
  config:
    import: configserver:${CLOUD_CONFIG_BASE_URL}
  cloud:
    config:
      uri: ${CLOUD_CONFIG_BASE_URL}  # Config Service
      fail-fast: false
      
jwt:
  password:
    encoder:
      secret: ${JWT_ENCODER_SECRET}
      iteration: 64
      keylength: 256
  secret: ${JWT_SECRET}
  access-token:
    expiration: 3600  # 1 hour
  refresh-token:
    expiration: 604800  # 7 days
  issuer: proselyte

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}

