spring:
  application:
    name: notification
  config:
    import: configserver:${CLOUD_CONFIG_BASE_URL}
  cloud:
    config:
      uri: ${CLOUD_CONFIG_BASE_URL:http://localhost:8888}  # Config Service
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}