spring:
  application:
    name: trip
  config:
    import: configserver:${CLOUD_CONFIG_BASE_URL}
  cloud:
    config:
      uri: ${CLOUD_CONFIG_BASE_URL}  # Config Service
      fail-fast: false

jwt:
  secret: ${JWT_SECRET}
  current-trip-id:
    expiration: 604800  # 7 days
  issuer: proselyte

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}